# Generated by Django 5.2.8 on 2025-11-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0002_borrowrequest_end_date_borrowrequest_start_date'),
        ('items', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='items.item'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='borrows.borrowrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request', 'Borrow Request'), ('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('reminder', 'Return Reminder'), ('overdue', 'Overdue'), ('returned', 'Item Returned'), ('rating', 'Rating Received'), ('message', 'New Message')], max_length=20),
        ),
    ]
